### ISSUE TITLE
下拉框内容会被

### ISSUE THREAD

**Issue by yun3948** [callmesoul/wepy-match-input#1]
页面在 wepyMatchInputChangeCallBack 函数内 设置 matchLIst 数据内容，会闪现然后隐藏，请问是什么原因呢？查看代码的话，好像inputChange 内清空了matchList 数据 ，VUE新手，请告知解决办法，谢谢

**Comment by callmesoul** [comment]
噢噢，大概是因为输入框的绑定，更改值的的时候双向绑定触发赃检测，会导致重新渲染。明天我处理下

**Comment by callmesoul** [comment]
看了下我这边没有这问题，因为我wepyMatchInputChangeCallBack 设置 matchLIst 数据内容是同过后台请求回来的数据去设置matchList的。
你的问题可能是inputChange 先触发了wepyMatchInputChangeCallBack 再清空matchList 。
这过程可能先触发了wepyMatchInputChangeCallBack ，然后执行了你在wepyMatchInputChangeCallBack 里设置了matchList的逻辑在执行了清空matchList 。一个先后问题。

新的0.0.4版本修复了先清空matchList再触发回调方法。你升级下看是否这问题？

**Comment by yun3948** [comment]
感谢回复。我这边的操作是首先获取了需要的全部数据，然后固定赋值，不再异步获取，所以可能引起了我所描述的情况，我修改下 再次感谢

**Comment by callmesoul** [comment]
你不用修改，更新插件应该就可以了

**Comment by yun3948** [comment]
已经更新解决 谢谢了

**Comment by callmesoul** [comment]
不客气
